/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {
    public static void main(String[] args) {
//        File file = new File("app/src/main/resources/recentquotes.json");
//        System.out.println(QuoteMapper.getDisplayedQuote(file));
        String apiUrl = "https://api.quotable.io/random";

        System.out.println(QuoteMapper.addRandomQuote(apiUrl));

    }
}
