/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.File;

public class App {
    public static void main(String[] args) {
        File file = new File("app/src/main/resources/recentquotes.json");
        System.out.println(QuoteMapper.getDisplayedQuote(file));
    }
}
